# - name: ping the server
#   hosts: web #which hosts your ansible server wants to connect
#   tasks: #list of tasks/modules/collections
#   - name: ping the server
#     ansible.builtin.ping:

- name: ping the server
  hosts: web
  tasks:
  - name: ping the server
    ansible.builtin.ping: