- name: nginx install and run
  hosts: web
  become: yes #sudo access
  tasks: 
    - name: install nginx
      ansible.builtin.package: #heterogeneous module that can work for all distributions
        name: nginx
        status: present
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
        

