- name: nginx installation and run
  hosts: local
  connection: local
  become: yes #giving sudo access to install nginx package
  tasks: 
    - name: nginx installation
      ansible.builtin.package: #heterogeneous module that can work for all distributions
        name: nginx
        state: absent
    - name: nginx run
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes