- name: nginx install and run
  hosts: web
#  connection: local #keep this, when you want to install nginx in ansible server
  become: yes #giving sudo access to install nginx package
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes