- name: variables
  hosts: local
  vars: #play level variables -> all tasks in this playbook have access to it
    course: "Devops"
    duration: "120hrs"
    trainer: "Haripriya G"
  tasks:
  - name: Print the information
    ansible.builtin.debug:
      msg: "Iam learning {{course}}, duration is {{duration}}, trainer name is {{trainer}}"
  
  - name: Print the information again
    vars: #task level variables can override play level variables
      course: "ansible"
    ansible.builtin.debug:
      msg: "Iam learning {{course}}, duration is {{duration}}, trainer name is {{trainer}}"