- name: variables
  hosts: 
  vars: #play level -> all tasks in this play have access to this
    COURSE: "DevOps with AWS"
    DURATION: "120 hrs"
    Trainer: "siva"
  tasks: 
  - name: Print the information
    ansible.builtin.debug:
      msg: "Iam learning DevOps with AWS, Duration is : 120 hrs, trainer is : siva"
      msg2: "Iam learning {{COURSE}}, Duration is : {{DURATION}}, trainer is : {trainer{}}"

  - name: Print the information
    vars: #task level variables override play level vars
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Iam learning DevOps with AWS, Duration is : 120 hrs, trainer is : siva"
      msg2: "Iam learning {{COURSE}}, Duration is : {{DURATION}}, trainer is : {trainer{}}"
  
  - name: Print the information
    ansible.builtin.debug:
      msg2: "Iam learning {{COURSE}}, Duration is : {{DURATION}}, trainer is : {trainer{}}"
