- name: Create expense user
  hosts: web
  become: yes #giving root access
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id expense
    register: USER #USER is a variable that gets output from above command
  
  - name: Print user information
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"
  # - name: Print the information
  #   ansible.builtin.debug:
  #     msg: "Expense user already exists"
  #   when: rc = 0

  - name: Create the user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0

