- name: Nginx installation
  hosts: local
  become: yes
  connection: local
  tasks:
  - name: Print the stats
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "Redhat"

  - name: install nginx if Debiam
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"
