- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: Print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible') }}"

  - name: convert to uppercase
    vars:
      greeting: "Hello Hari"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert to lowercase
    vars:
      greeting: "Hello Hari"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: get the unique values
    vars:
      numbers: [1,4,7,4,6,20,5,7]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the min and max values
    vars:
      numbers: [1,4,7,4,6,20,5,7]
    ansible.builtin.debug:
      msg: "Min: {{ numbers | min }}, max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course: 
        name: DevOps
        duration: 120
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - {"key": "name","value": "DevOps"}
      - {"key": "duration","value": "120"}
      - {"key": "trainer","value": "sivakumar"}
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"