- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0d87ebcb7cf7baafe
    sg_id: sg-0b620932ce14422f3
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
    zone: haridev.online
  tasks: 
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t2.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      state: "present"
    loop: "{{ instances }}"
    register: ec2_instances
    
  #     #private IP R53
  # - name: create r53 private records
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ zone }}"
  #     record: "{{ item.item }}.{{ zone }}" #mysql.daws81s.online
  #     type: A
  #     ttl: 1
  #     value: "{{ item.instances[0].private_ip_address }}"
  #     wait: true
  #     #overwrite: true
  #   loop: "{{ ec2_instances.results }}"

  # - name: create r53 public record for frontend
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ zone }}"
  #     record: "{{ zone }}" #daws81s.online
  #     type: A
  #     ttl: 1
  #     value: "{{ item.instances[0].public_ip_address }}"
  #     wait: true
  #     #overwrite: true
  #   loop: "{{ ec2_instances.results }}"
  #   when: item.item == "frontend" #when keyword should not have {{}}