- name: variables from files
  hosts: local
  vars_files:
    vars-declrtn.yaml
  tasks:
  - name: Print the information
    ansible.builtin.debug:
      msg: "Learning {{course}}, duration {{duration}}, trainer {{trainer}}"