- name: variables
  hosts: web
  vars:
    course: "Devops"
    duration: "120hrs"
    trainer: "Haripriya G"
  tasks:
  - name: Print the information
    ansible.builtin.debug:
      msg: "Iam learning {{course}}, duration is {{duration}}, trainer name is {{trainer}}"
  
  - name: Print the information again
    ansible.builtin.debug:
      course: "ansible"
      msg: "Iam learning {{course}}, duration is {{duration}}, trainer name is {{trainer}}"